version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/testdeploy
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 644
     type:
       - file
#hooks:
#   BeforeInstall:
#    - location: scripts/installapache.sh
#      runas: root
#    - location: scripts/startapache.sh
#      runas: root
#   AfterInstall:
#    - location: scripts/restartapache.sh
#      runas: root

